import type { Metadata } from "next";
import "@/styles/globals.css"
import { Inter as FontSans } from "next/font/google"
import {NextUIProvider} from "@nextui-org/react";

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/context/ThemeContext";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark scroll-smooth'>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <NextUIProvider>
        <ThemeProvider>
          {children}
        </ThemeProvider>
        </NextUIProvider>
        </body>
    </html>
  );
}
